"""Static reference data for Romanian județe (counties)."""
from __future__ import annotations

JUDETE: list[dict[str, str]] = [
    {"code": "AB", "name": "Alba"},
    {"code": "AR", "name": "Arad"},
    {"code": "AG", "name": "Argeș"},
    {"code": "BC", "name": "Bacău"},
    {"code": "BH", "name": "Bihor"},
    {"code": "BN", "name": "Bistrița-Năsăud"},
    {"code": "BT", "name": "Botoșani"},
    {"code": "BV", "name": "Brașov"},
    {"code": "BR", "name": "Brăila"},
    {"code": "B",  "name": "București"},
    {"code": "BZ", "name": "Buzău"},
    {"code": "CS", "name": "Caraș-Severin"},
    {"code": "CL", "name": "Călărași"},
    {"code": "CJ", "name": "Cluj"},
    {"code": "CT", "name": "Constanța"},
    {"code": "CV", "name": "Covasna"},
    {"code": "DB", "name": "Dâmbovița"},
    {"code": "DJ", "name": "Dolj"},
    {"code": "GL", "name": "Galați"},
    {"code": "GR", "name": "Giurgiu"},
    {"code": "GJ", "name": "Gorj"},
    {"code": "HR", "name": "Harghita"},
    {"code": "HD", "name": "Hunedoara"},
    {"code": "IL", "name": "Ialomița"},
    {"code": "IS", "name": "Iași"},
    {"code": "IF", "name": "Ilfov"},
    {"code": "MM", "name": "Maramureș"},
    {"code": "MH", "name": "Mehedinți"},
    {"code": "MS", "name": "Mureș"},
    {"code": "NT", "name": "Neamț"},
    {"code": "OT", "name": "Olt"},
    {"code": "PH", "name": "Prahova"},
    {"code": "SM", "name": "Satu Mare"},
    {"code": "SJ", "name": "Sălaj"},
    {"code": "SB", "name": "Sibiu"},
    {"code": "SV", "name": "Suceava"},
    {"code": "TR", "name": "Teleorman"},
    {"code": "TM", "name": "Timiș"},
    {"code": "TL", "name": "Tulcea"},
    {"code": "VS", "name": "Vaslui"},
    {"code": "VL", "name": "Vâlcea"},
    {"code": "VN", "name": "Vrancea"},
]

JUDETE_BY_CODE: dict[str, str] = {j["code"]: j["name"] for j in JUDETE}
